name: Build and deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Perpare npm
        uses: bahmutov/npm-install@v1
      - name: Build Site
        run: |
          npm install -g typescript
          make build-linux
      - name: Deploy to GHPages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
